num = int(input('DIgite um número inteiro:'));
num2 = int(input('Digite outro número inteiro:'));
print('A soma é: {}'.format(num + num2));
print('A subtração é: {}'.format(num - num2));
print('A multiplicação é: {}'.format(num * num2));
print('A divisão é: {}'.format(num / num2));
print('A divisão inteira é: {}'.format(num // num2));
print('A potência é: {}'.format(num ** num2));
print('O resto da divisão é: {}'.format(num % num2));
print('A média é: {}'.format((num + num2) / 2));
print('A raiz quadrada é: {}'.format(num ** (1/2)));
print('A raiz cúbica é: {}'.format(num ** (1/3)));